version: '3.8'
services:
  server:
    build: ./server/
    container_name: server
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./server:/app
      
  client:
    build: ./web/
    container_name: client_frontend
    depends_on:
      - server
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./web:/app
    stdin_open: true
    tty: true
